LANGCODES = {
    "(default)" : "",
    "Arabic" : "lang_ar",
    "Bulgarian" : "lang_bg",
    "Catalan" : "lang_ca",
    "Czech" : "lang_cs",
    "Danish" : "lang_da",
    "German" : "lang_de",
    "Greek" : "lang_el",
    "English" : "lang_en",
    "Spanish" : "lang_es",
    "Estonian" : "lang_et",
    "Finnish" : "lang_fi",
    "French" : "lang_fr",
    "Croatian" : "lang_hr",
    "Hungarian" : "lang_hu",
    "Indonesian" : "lang_id",
    "Icelandic" : "lang_is",
    "Italian" : "lang_it",
    "Hebrew" : "lang_iw",
    "Japanese" : "lang_ja",
    "Korean" : "lang_ko",
    "Lithuanian" : "lang_lt",
    "Latvian" : "lang_lv",
    "Dutch" : "lang_nl",
    "Norwegian" : "lang_no",
    "Polish" : "lang_pl",
    "Portuguese" : "lang_pt",
    "Romanian" : "lang_ro",
    "Russian" : "lang_ru",
    "Slovak" : "lang_sk",
    "Slovenian" : "lang_sl",
    "Serbian" : "lang_sr",
    "Swedish" : "lang_sv",
    "Turkish" : "lang_tr",
    "Chinese (Simplified)" : "lang_zh-CN",
    "Chinese (Traditional)" : "lang_zh-TW"
}
